WebMvc_Training/WebMvc_Training.WebUI/Controllers/FacultyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMvc_Training.Business.DanangUniversityBusiness.IBusiness;
using WebMvc_Training.Business.ViewModel;

namespace WebMvc_Training.WebUI.Controllers
{
    public class FacultyController : BaseController
    {
        private IFacultyBusiness _Business;

        public FacultyController(IFacultyBusiness business)
        {
            _Business = business;
        }

        // GET: Faculty
        public ActionResult List()
        {
            var model = _Business.GetAll();
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var model = _Business.GetSingle(id);
            return PartialView(model);
        }

        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult CreatePost(FacultyViewModel viewModel)
        {
            _Business.Add(viewModel);
            return Json(new { Message = "Success" });
        }

        public ActionResult Edit(int id)
        {
            var model = _Business.GetSingle(id);
            return PartialView(model);
        }

        public ActionResult EditPost(FacultyViewModel viewModel)
        {
            _Business.Edit(viewModel);
            return Json(new { Message = "Success" });
        }

        public ActionResult Delete(int id)
        {
            _Business.Delete(id);
            return Json(new { Message = "Success" });
        }
    }
}

WebMvc_Training/WebMvc_Training.WebUI/Views/Faculty/Create.cshtml
<h2>Them moi ban ghi</h2>

<br />

<form class="formAction">
    <div class="form-group row">
        <label class="col-md-2" style="font-size: 120%;">Faculty Name: </label>
        <div class="col-md-6">
            <input class="form-control required" name="FacultyName" />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-md-2" style="font-size: 120%;">Description</label>
        <div class="col-md-6">
            <textarea class="form-control" name="Description" rows="5" />
        </div>
    </div>

    <br/> 

    <div style="float:left;">
        <input type="button" class="btn btn-primary" value="Create" style="width: 80px;" onclick="Load.Action('/Faculty/CreatePost', '/Faculty/List')" />

        <a href="@Url.Action("List", "Faculty")">
            <input type="button" class="btn btn-primary" value="Back" style="width: 80px;" />
        </a>
    </div>
    
    <div style="clear: left;"></div>
    
    <br/>

    <p id="error"></p>
</form>

<input type="hidden" id="status" value="0"/>

WebMvc_Training/WebMvc_Training.WebUI/Views/Faculty/Detail.cshtml
@model WebMvc_Training.Business.ViewModel.FacultyViewModel

<!---->
<div class="panel-heading">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1primary" data-toggle="tab">Thong tin</a></li>
    </ul>
</div>
<div class="panel-body">
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab1primary">
            <div class="form-group row">
                <label class="col-md-2" style="font-size: 120%;">FacultyId</label>
                <div class="col-md-6">
                    <input class="form-control" value="@Model.FacultyId" disabled />
                </div>
            </div>

            <div class="form-group row">
                <label class="col-md-2" style="font-size: 120%;">FacultyName</label>
                <div class="col-md-6">
                    <input class="form-control" value="@Model.FacultyName" disabled />
                </div>
            </div>

            <div class="form-group row">
                <label class="col-md-2" style="font-size: 120%;">Description</label>
                <div class="col-md-6">
                    <textarea class="form-control" rows="5" disabled>@Model.Description</textarea>
                </div>
            </div>
        </div>
    </div>
</div>

<br/>
<br/>

<a href="@Url.Action("List", "Faculty")">
    <input type="button" class="btn btn-primary" value="Back" style="width: 80px;" />
</a>

WebMvc_Training/WebMvc_Training.WebUI/Views/Faculty/Edit.cshtml
@model WebMvc_Training.Business.ViewModel.FacultyViewModel

<div class="panel-heading">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1primary" data-toggle="tab">Chinh sua thong tin</a></li>
    </ul>
</div>

<div class="panel-body">
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab1primary">

            <form class="formAction">

                <div class="form-group row">
                    <label class="col-md-2" style="font-size: 120%;">FacultyId</label>
                    <div class="col-md-6">
                        <input class="form-control" value="@Model.FacultyId" name="FacultyId" readonly />
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-md-2" style="font-size: 120%;">FacultyName</label>
                    <div class="col-md-6">
                        <input class="form-control" value="@Model.FacultyName" name="FacultyName" />
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-md-2" style="font-size: 120%;">Description</label>
                    <div class="col-md-6">
                        <textarea class="form-control" rows="5" name="Description">@Model.Description</textarea>
                    </div>
                </div>

                <div style="float: left">
                    <input type="button" class="btn btn-primary" onclick="Load.Action('/Faculty/EditPost', '/Faculty/List')" value="Update" style="width: 80px;" />

                    <a href="@Url.Action("List", "Faculty")">
                        <input type="button" class="btn btn-primary" value="Back" style="width: 80px;" />
                    </a>
                </div>

                <div style="clear: both;"></div>

                <br />

                <p id="error"></p>
            </form>

        </div>

    </div>
</div>

<input type="hidden" id="status" value="0" />

WebMvc_Training/WebMvc_Training.WebUI/Views/Faculty/List.cshtml
@model IEnumerable<WebMvc_Training.Business.ViewModel.FacultyViewModel>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh sach khoa </h2>

<table class="table table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @{  int i = 1; }

        @foreach (var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>@item.FacultyName</td>
                <td><a href="#" onclick="Load.LoadPage('/Faculty/Detail', @item.FacultyId)">Detail</a></td>
                <td><a href="#" onclick="Load.LoadPage('/Faculty/Edit', @item.FacultyId)">Edit</a></td>
                <td><a href="#" onclick="Load.DeleteAction('/Faculty/Delete', '/Faculty/List', @item.FacultyId, 0)">Delete</a></td>
            </tr>

            i++;
        }
    </tbody>
</table>

<br/>

<input type="button" value="Create" class="btn btn-primary" style="width: 80px;" onclick="Load.LoadPage('/Faculty/Create');"/>